<a href="https://colab.research.google.com/github/pragati6412/NumPy-Array/blob/main/numpy5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array([[1,2,3,4,5,6],[12,11,10,9,8,7],[13,14,15,16,17,18]])

In [ ]:
np.sort(arr,axis=0,kind='mergesort')

array([[ 1,  2,  3,  4,  5,  6],
       [12, 11, 10,  9,  8,  7],
       [13, 14, 15, 16, 17, 18]])

In [ ]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [12, 11, 10,  9,  8,  7],
       [13, 14, 15, 16, 17, 18]])

In [ ]:
np.sort(arr,kind='mergesort')

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])