<a href="https://colab.research.google.com/github/pragati6412/NumPy-Array/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np

In [3]:
np.random.random()

0.4414447772710215

In [4]:
np.random.random((3,1))

array([[0.8944718 ],
       [0.74033135],
       [0.41360347]])

In [5]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [7]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
arr=np.random.random((3,4))

In [9]:
arr

array([[0.39037048, 0.83069062, 0.11067193, 0.72006947],
       [0.99804209, 0.0155699 , 0.93041191, 0.98966674],
       [0.88665719, 0.40506145, 0.13534644, 0.92012167]])

In [10]:
arr=np.reshape(arr,(4,3))

In [11]:
arr

array([[0.39037048, 0.83069062, 0.11067193],
       [0.72006947, 0.99804209, 0.0155699 ],
       [0.93041191, 0.98966674, 0.88665719],
       [0.40506145, 0.13534644, 0.92012167]])

In [12]:
arr.flatten()

array([0.39037048, 0.83069062, 0.11067193, 0.72006947, 0.99804209,
       0.0155699 , 0.93041191, 0.98966674, 0.88665719, 0.40506145,
       0.13534644, 0.92012167])