<a href="https://colab.research.google.com/github/pragati6412/NumPy-Array/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
print(arr+1)
print(arr-1)
print(arr*2)
print(arr/1)
print(arr**2)

[2 3 4 5 6]
[0 1 2 3 4]
[ 2  4  6  8 10]
[1. 2. 3. 4. 5.]
[ 1  4  9 16 25]


In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr.max()

5

In [ ]:
arr.min()

1

In [ ]:
arr1=np.array([[1,3,5],[2,1,2],[1,1,1]])

In [ ]:
arr1.max(axis=0)

array([2, 3, 5])

In [ ]:
arr1.max(axis=1)

array([5, 2, 1])

In [ ]:
arr1.min(axis=0) # column wise

array([1, 1, 1])

In [ ]:
arr1.min(axis=1)

array([1, 1, 1])

In [ ]:
arr1.sum()

17