<a href="https://colab.research.google.com/github/pragati6412/NumPy-Array/blob/main/Numpy6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([[1,2,3,4,5],
              [5,4,3,2,1]])

In [ ]:
arr2=np.array([[5,4,3,2,1],
               [1,2,3,4,5]])

In [ ]:
arr1

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [ ]:
arr2

array([[5, 4, 3, 2, 1],
       [1, 2, 3, 4, 5]])

In [ ]:
arr=np.vstack((arr1,arr2))

In [ ]:
arr

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [5, 4, 3, 2, 1],
       [1, 2, 3, 4, 5]])

In [ ]:
arr=np.hstack((arr1,arr2))

In [ ]:
arr

array([[1, 2, 3, 4, 5, 5, 4, 3, 2, 1],
       [5, 4, 3, 2, 1, 1, 2, 3, 4, 5]])

In [ ]:
arr=np.hsplit(arr,2)

In [ ]:
arr

[array([[1, 2, 3, 4, 5],
        [5, 4, 3, 2, 1]]), array([[5, 4, 3, 2, 1],
        [1, 2, 3, 4, 5]])]

In [ ]:
arr=np.vsplit(arr,2)

AttributeError: ignored

In [ ]:
arr=np.concatenate((arr1,arr2),axis=0)

In [ ]:
arr

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [5, 4, 3, 2, 1],
       [1, 2, 3, 4, 5]])