<a href="https://colab.research.google.com/github/pragati6412/NumPy-Array/blob/main/Numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr2=np.array([[7,8,9],
               [4,5,6],
               [1,2,3]])

In [ ]:
arr1+arr2

array([[ 8, 10, 12],
       [ 8, 10, 12],
       [ 8, 10, 12]])

In [ ]:
arr1*arr2

array([[ 7, 16, 27],
       [16, 25, 36],
       [ 7, 16, 27]])

In [ ]:
arr1.dot(arr2)

array([[ 18,  24,  30],
       [ 54,  69,  84],
       [ 90, 114, 138]])

In [ ]:
arr2.dot(arr1)

array([[102, 126, 150],
       [ 66,  81,  96],
       [ 30,  36,  42]])

In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
arr[:2]

array([1, 2])

In [ ]:
arr[2:-1]

array([3, 4])

In [ ]:
arr1[1:,:1]

array([[4],
       [7]])

In [ ]:
arr1[:1,1:-1]